MUJOCO:
  ENV: 'HalfCheetahEnv'
  MAX_HORIZON_STEPS: 100
  GAMMA: 0.98
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    LAYERS:
      - 64
      - 16
      - 8
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.001
  BIAS_LR_FACTOR: 2
  STD_LR_FACTOR: 0.5
  BATCH_SIZE: 8
