MUJOCO:
  ENV: 'HandModelTSLAdjustedEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  BATCH_SIZE: 1
  EPOCHS: 1000
  NSTEPS_FOR_BACKWARD: 2
  FRAME_SKIP: 20
  TIMESTEP: 0.002
  POLICY:
    ARCH: 'Perttu'
    METHOD: 'R-VO'
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    MAX_HORIZON_STEPS: 50
    INITIAL_SD: 0.2
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.0
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 1.0
  ADAM_BETAS: (0.9, 0.999)
LOG:
  TESTING:
    ENABLED: True
    ITER_PERIOD: 1
    RECORD_VIDEO: true