MUJOCO:
  ENV: 'HopperEnv'
  GAMMA: 0.98
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    MAX_HORIZON_STEPS: 120
    LAYERS:
      - 64
      - 64
      - 32
      - 8
    NORM_LAYERS:
      - 0
      - 1
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.001
  BIAS_LR_FACTOR: 2
  STD_LR_FACTOR: 0.5
  BATCH_SIZE: 32
