MUJOCO:
  ENV: 'InvertedDoublePendulumEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  BATCH_SIZE: 8
  FRAME_SKIP: 4
  RANDOM_SEED: 30
  EPOCHS: 5001
  POLICY:
    ARCH: 'Perttu'
    METHOD: 'R-VO'
    NETWORK: False
    MAX_HORIZON_STEPS: 50
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    INITIAL_LOG_SD: -0.5
    INITIAL_SD: 0.2
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.1
    GRAD_WEIGHTS: "average"
SOLVER:
  OPTIMIZER: 'adam'
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 1.0
  ADAM_BETAS: (0.9, 0.999)
LOG:
  TESTING:
    ITER_PERIOD: 100
    RECORD_VIDEO: True
