MUJOCO:
  ENV: 'InvertedDoublePendulumEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    MAX_HORIZON_STEPS: 100
    ARCH: 'VariationalOptimization'
    METHOD: 'PR'
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    BATCH_SIZE: 32
    INITIAL_LOG_SD: -3.0
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.01
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 2.0
  ADAM_BETAS: (0.9, 0.999)
