MUJOCO:
  ENV: 'InvertedPendulumEnv'
  MAX_HORIZON_STEPS: 100
  CLIP_ACTIONS: false
  GAMMA: 0.95
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    LAYERS:
      - 32
      - 16
      - 8
    NORM_LAYERS:
      - 0
      - 1
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2
  STD_LR_FACTOR: 2
  BATCH_SIZE: 8
