MUJOCO:
  ENV: 'InvertedDoublePendulumEnv'
  MAX_HORIZON_STEPS: 50
  GAMMA: 0.98
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    ARCH: 'DeterministicPolicy'
    LAYERS:
      - 64
      - 64
      - 32
      - 8
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.001
  BIAS_LR_FACTOR: 2
  STD_LR_FACTOR: 0.01
  BATCH_SIZE: 16
