MUJOCO:
  ENV: 'InvertedPendulumEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  BATCH_SIZE: 1
  POLICY:
    MAX_HORIZON_STEPS: 50
    ARCH: 'Perttu'
    METHOD: 'Grad'
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    INITIAL_LOG_SD: -1.0
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.0
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 100.0
  ADAM_BETAS: (0.9, 0.999)
