MUJOCO:
  ENV: 'SwimmerEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  BATCH_SIZE: 8
  FRAME_SKIP: 10
  EPOCHS: 5000
  POLICY:
    ARCH: 'Perttu'
    METHOD: 'R-VO'
    NETWORK: False
    MAX_HORIZON_STEPS: 40
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    INITIAL_LOG_SD: -0.5
    INITIAL_SD: 0.5
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.0
    PRIORITISE: False
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 1.0
  ADAM_BETAS: (0.9, 0.999)
LOG:
  TESTING:
    ITER_PERIOD: 200
    RECORD_VIDEO: True
