MUJOCO:
  ENV: 'SwimmerEnv'
  CLIP_ACTIONS: false
MODEL:
  META_ARCHITECTURE: 'Basic'
  POLICY:
    ARCH: 'VariationalOptimization'
    METHOD: 'PR'
    MAX_HORIZON_STEPS: 200
    LAYERS:
      - 128
      - 128
    GAMMA: 0.99
    BATCH_SIZE: 1
    INITIAL_LOG_SD: -0.5
    INITIAL_ACTION_MEAN: 0.0
    INITIAL_ACTION_SD: 0.1
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1
  STD_LR_FACTOR: 10.0
  ADAM_BETAS: (0.9, 0.999)
